learningTemplates/app1/urls.py
from django.urls import path
from app1 import views

#TEMPLATE TAGGING
app_name = 'app1'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learningTemplates/learningTemplates/urls.py
from django.contrib import admin
from django.urls import path, include
from app1 import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls'))
]

learningTemplates/app1/models.py
from django.db import models

# Create your models here.

learningTemplates/app1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    contextDict = {'text':'hello', 'number':100}
    return render(request, 'app1/index.html', contextDict)

def other(request):
    return render(request, 'app1/other.html')

def relative(request):
    return render(request, 'app1/relative_url.html')

learningTemplates/templates/app1/base.html
<!DOCTYPE html>
{% load filters %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active"><a class="nav-link" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'app1:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!--Anything outside of this will be inherited if you extend-->
      {% endblock %}
    </div>
  </body>
</html>

learningTemplates/templates/app1/index.html
<!DOCTYPE html>
{% extends "app1/base.html" %}
  {% block body_block %}
    <h1>Welcome to INDEX!</h1>
    <h2>This is index.html showing</h2>
    <h1>{{ text|cut:'e' }}</h1>
    <h1>{{ number|add:"69" }}</h1>
  {% endblock %}

learningTemplates/templates/app1/other.html
<!DOCTYPE html>
{% extends "app1/base.html" %}
  {% block body_block %}
    <h1>Welcome to OTHER!</h1>
    <h2>This is an example of template inheritance!</h2>
  {% endblock %}

learningTemplates/templates/app1/relative_url.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to RELATIVE URL TEMPLATES!!!</h1>
    <a href="{% url 'app1:other' %}">OTHER</a>
    <a href="{% url 'admin:index' %}">INDEX</a>
    <a href="{% url 'index' %}">INDEX LINK</a>
  </body>
</html>