learningUsers/app1/urls.py
from django.urls import path
from app1 import views

#TEMPLATE URLs
app_name = 'app1'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('userLogin/',views.userLogin,name='userLogin')
]

learningUsers/learningUsers/urls.py
from django.contrib import admin
from django.urls import path, include
from app1 import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/',admin.site.urls),
    path('app1/',include('app1.urls')),
    path('userLogout/',views.userLogOut,name='userLogOut'),
    path('special',views.special,name='special'),
]

learningUsers/app1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional classes
    portfolio = models.URLField(blank=True)
    profilePic = models.ImageField(upload_to='profilePics',blank=True)

    def __str__(self):
        return self.user.username

learningUsers/app1/forms.py
from django import forms
from django.contrib.auth.models import User
from app1.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio','profilePic')

learningUsers/app1/views.py
from django.shortcuts import render
from app1.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse

# Create your views here.
def index(request):
    return render(request,'app1/index.html')

@login_required
def special(request):
    return HttpResponse('You are logged in, NICE!')

@login_required
def userLogOut(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        userForm = UserForm(data=request.POST)
        profileForm = UserProfileInfoForm(data=request.POST)

        if userForm.is_valid() and profileForm.is_valid():
            user = userForm.save()
            user.set_password(user.password)
            user.save()

            profile = profileForm.save(commit=False)
            profile.user = user

            if 'profilePic' in request.FILES:
                profile.profilePic = request.FILES['profilePic']

            profile.save()

            registered = True
        else:
            print(userForm.errors,profileForm.errors)
    else:
        userForm = UserForm()
        profileForm = UserProfileInfoForm()

    return render(request,'app1/registration.html',
                {'userForm':userForm,
                'profileForm':profileForm,
                'registered':registered})

def userLogin(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active():
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE!')
        else:
            print('Someone tried to login and failed')
            print('Username: {} and password: {}'.format(username,password))
            return HttpResponse('invalid login details supplied')
    else:
        return render(request, 'app1/login.html', {})

learningUsers/templates/app1/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active"><a class="nav-link" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'app1:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'userLogOut' %}">Log Out</li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'app1:userLogin' %}">Log In</li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>
  </body>
</html>

learningUsers/templates/app1/index.html
{% extends "app1/base.html" %}
  {% block body_block %}

  <div class="jumbotron">
    <h1>django Level Five</h1>
  </div>

  {% endblock %}

learningUsers/templates/app1/login.html
{% extends "app1/base.html" %}
{% block body_block %}
  <div class="container">
    <h1>Please Login</h1>
    <form action="{% url 'app1:userLogin' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" value="" placeholder="Enter username">
      <label for="password">Password:</label>
      <input type="text" name="password" value="">
      <input type="submit" class="btn btn-default" name="" value="Login">
    </form>
  </div>
{% endblock %}

learningUsers/templates/app1/registration.html
{% extends "app1/base.html" %}
  {% block body_block %}

    <div class="jumbotron">

      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register here!</h1>
        <h3>Fill out the form:</h3>
        <form method="post" enctype="multipart/form-data">

          {% csrf_token %}
          {{ userForm.as_p }}
          {{ profileForm.as_p }}
          <input type="submit" class="btn btn-default" name="" value="Register">

        </form>
      {% endif %}

    </div>

  {% endblock %}